INSERT INTO ppl_title(title) VALUES ('Mr.');
INSERT INTO ppl_title(title) VALUES ('Mrs.');
INSERT INTO ppl_title(title) VALUES ('Miss');
INSERT INTO ppl_title(title) VALUES ('Dr.');
INSERT INTO ppl_title(title) VALUES ('Ms.');
INSERT INTO ppl_title(title) VALUES ('Prof.');
INSERT INTO ppl_title(title) VALUES ('Rev.');
INSERT INTO ppl_title(title) VALUES ('Lady');
INSERT INTO ppl_title(title) VALUES ('Sir');
INSERT INTO ppl_title(title) VALUES ('Capt.');
INSERT INTO ppl_title(title) VALUES ('Major');
INSERT INTO ppl_title(title) VALUES ('Lt.-Col.');
INSERT INTO ppl_title(title) VALUES ('Col.');
INSERT INTO ppl_title(title) VALUES ('Lady');
INSERT INTO ppl_title(title) VALUES ('Lt.-Cmdr.');
INSERT INTO ppl_title(title) VALUES ('The Hon.');
INSERT INTO ppl_title(title) VALUES ('Cmdr.');
INSERT INTO ppl_title(title) VALUES ('Flt. Lt.');
INSERT INTO ppl_title(title) VALUES ('Brgdr.');
INSERT INTO ppl_title(title) VALUES ('Judge');
INSERT INTO ppl_title(title) VALUES ('Lord');
INSERT INTO ppl_title(title) VALUES ('The Hon. Mrs');
INSERT INTO ppl_title(title) VALUES ('Wng. Cmdr.');
INSERT INTO ppl_title(title) VALUES ('Group Capt.');
INSERT INTO ppl_title(title) VALUES ('Rt. Hon. Lord');
INSERT INTO ppl_title(title) VALUES ('Revd. Father');
INSERT INTO ppl_title(title) VALUES ('Revd Canon');
INSERT INTO ppl_title(title) VALUES ('Maj.-Gen.');
INSERT INTO ppl_title(title) VALUES ('Air Cdre.');
INSERT INTO ppl_title(title) VALUES ('Viscount');
INSERT INTO ppl_title(title) VALUES ('Dame');
INSERT INTO ppl_title(title) VALUES ('Rear Admrl.');